# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "nutrication-app"
client_id = "e86e07aec7baf1f4fd940f2d9e7ee093"
application_url = "https://williams-ballot-translator-humans.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://williams-ballot-translator-humans.trycloudflare.com/auth/callback",
  "https://williams-ballot-translator-humans.trycloudflare.com/auth/shopify/callback",
  "https://williams-ballot-translator-humans.trycloudflare.com/api/auth/callback",
  "https://williams-ballot-translator-humans.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rju-app-store.myshopify.com"
